cdk:
  stage: "dev"
  domainNames: 
    main: "thantzin.ovh"
    ec2: "ec2.thantzin.ovh"
    ecs: "ecs.thantzin.ovh"
  region: "ap-northeast-1"
  enableAPILambda: false # to toggle, also requires for SPA config
  enableEc2: false # to toggle
  ssm:
    mainSite:
      globalCertificateArnPath: "/certificates/global/dev/thantzin_ovh"
    ec2:
      globalCertificateArnPath: "/certificates/global/dev/thantzin_ovh"
      localCertificateArnPath: "/certificates/local/dev/ec2-alb_thantzin_ovh"
  allowedOrigins: 
    - "https://localhost:8443"
    - "http://localhost:8443"
    - "http://thantzin.ovh"
    - "https://thantzin.ovh"


